/* Generated by tools/make_cpc_tables.py - do not edit. */
#ifndef TABLES_H
#define TABLES_H
#include <stdint.h>
extern const uint8_t cpc_glyphs[632];
extern const uint8_t cpc_game_tab[512];
extern const uint8_t cpc_cells[2864];
extern const uint8_t cpc_game_idx[256];
extern const uint8_t cpc_title_idx[256];
extern const uint8_t cpc_lut[288];
extern const uint8_t cpc_player_schemes[4];
extern const uint8_t cpc_palette[4];
#endif
