/* Generated by tools/extract_data.py - do not edit. */
#ifndef DATA_H
#define DATA_H
#include <stdint.h>
extern const uint8_t game_table[512];
extern const uint8_t title_table[180];
extern const uint8_t title_logo[240];
extern const uint8_t blast_pattern[64];
extern const char str_legend1[];
extern const char str_box_tl[];
extern const char str_box_ml[];
extern const char str_legend2[];
extern const char str_box2_t[];
extern const char str_box2_m[];
extern const char str_box2_b[];
extern const char str_box3_t[];
extern const char str_box3_m[];
extern const char str_box3_b[];
extern const char str_down[];
extern const char str_push_space[];
extern const char str_copyright[];
extern const char str_legend_row7[];
extern const char str_legend_row8[];
extern const char str_hud_score[];
extern const char str_hud_bonus[];
extern const char str_hud_stage[];
#endif
