/* Generated by tools/extract_data.py - do not edit. Logical code -> MZ display code and attribute. */
#ifndef TABLES_H
#define TABLES_H
#include <stdint.h>
extern const uint8_t game_table[512];
extern const uint8_t title_table[512];
#endif
