#!/usr/bin/env python3
"""Extract the data tables of the original bomber.mzf into c/data.c."""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
mzf = open(os.path.join(here, '..', 'bomber.mzf'), 'rb').read()
body = mzf[128:]
ORG = 0x1200
def at(a, n=1): return body[a - ORG:a - ORG + n]

def carray(name, data, per=16, comment=None):
    out = [f'/* {comment} */' if comment else '', f'const uint8_t {name}[{len(data)}] = {{']
    for i in range(0, len(data), per):
        out.append('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i + per]) + ',')
    out.append('};\n')
    return '\n'.join(o for o in out if o is not None)

def cstring(name, data, comment=None):
    """C string literal; a hex escape is closed before a following hex digit."""
    s = ''
    prev_hex = False
    for b in data:
        c = chr(b)
        if 0x20 <= b < 0x7f and c not in '"\\':
            if prev_hex and c in '0123456789abcdefABCDEF':
                s += '" "'
            s += c
            prev_hex = False
        else:
            s += f'\\x{b:02x}'
            prev_hex = True
    return (f'/* {comment} */\n' if comment else '') + f'const char {name}[] = "{s}";\n'

def zstring(a):
    b = bytearray()
    while at(a)[0]: b.append(at(a)[0]); a += 1
    return bytes(b)

parts = ['/* Generated by tools/extract_data.py from bomber.mzf - do not edit. */',
         '#include <stdint.h>', '#include "data.h"', '']
# ---- game table: original bytes plus documented patches on FREE codes only.
# Used by the game: 00-09 digits, 0A/0B/1A/1B bonus, 0E/0F/1E/1F exit, 10-19 HUD
# letters, 20 space, 21 colon, 22-41 monster death frames, 40-5F player death
# frames, 60-7F bomb frames, 80-89 bricks/walls, 8A-8D/9A-9D player, 90/91 icons,
# C0-DF monsters, E0-FF fire. Free: 0C 0D 1C 1D 8E 8F 92-99 9E 9F A0-BF.
gt = bytearray(at(0x2F4F, 512))
FREE = set([0x0C, 0x0D, 0x1C, 0x1D, 0x8E, 0x8F, 0x9E, 0x9F] + list(range(0x92, 0x9A)) + list(range(0xA0, 0xC0)))
# players 2..4: copies of the player-1 glyphs (8A/8B/9A/9B, 8C/8D/9C/9D) in other colours
colours = [(0x20, 0x30), (0x50, 0x10), (0x60, 0x70)]
for i, (ca, cb) in enumerate(colours):
    for frame, (src, attr) in enumerate(((0x8A, ca), (0x8C, cb))):
        dst = 0xA0 + i * 4 + frame * 2
        for dx, dy in ((0, 0), (1, 0), (0, 16), (1, 16)):
            gt[2 * (dst + dx + dy)] = gt[2 * (src + dx + dy)]
            gt[2 * (dst + dx + dy) + 1] = attr
# HUD letters (display A=01h..Z=1Ah), white
for i, ch in enumerate('PLMAYDHI'):
    gt[2 * (0x92 + i)] = ord(ch) - ord('A') + 1
    gt[2 * (0x92 + i) + 1] = 0x70
for code, ch in ((0x8E, 'W'), (0x8F, 'K'), (0x9E, 'V'), (0x9F, 'X')):
    gt[2 * code] = ord(ch) - ord('A') + 1
    gt[2 * code + 1] = 0x70
# box drawing for game-mode message frames, yellow: 0C horizontal, 0D vertical,
# 1C/1D top corners, AC/AD bottom corners
for code, disp in ((0x0C, 0x78), (0x0D, 0x79), (0x1C, 0x5C), (0x1D, 0x5D), (0xAC, 0x1C), (0xAD, 0x1D)):
    gt[2 * code] = disp
    gt[2 * code + 1] = 0x60
orig = at(0x2F4F, 512)
for code in range(256):
    if code not in FREE:
        assert gt[2 * code:2 * code + 2] == orig[2 * code:2 * code + 2], 'game_table patched a used code %02X' % code
parts.append(carray('game_table', bytes(gt), 16,
                    'logical code -> (display code, attribute), game mode; original 2F4Fh plus '
                    'players 2..4 (A0h-BBh), HUD letters and box glyphs on free codes'))

# ---- title table: full 256 entries so the title can use codes the game reserves.
# 00-5A: the original title table (letters, box drawing, logo blocks) plus Z;
# 5B-FF: the game table (legend sprites, digits...), with a yellow alphabet at
# 60-79, yellow digits at 7A-7F (0-5) and 25-28 (6-9), yellow dash at 29 -
# codes the title never uses for graphics.
tt = bytearray(gt)
tt[0:180] = at(0x314F, 180)
tt[2 * 0x5A:2 * 0x5A + 2] = bytes([0x1A, 0x70])
for i in range(26):
    tt[2 * (0x60 + i)] = i + 1
    tt[2 * (0x60 + i) + 1] = 0x60
for d in range(10):
    code = 0x7A + d if d < 6 else 0x25 + d - 6
    tt[2 * code] = 0x20 + d
    tt[2 * code + 1] = 0x60
tt[2 * 0x29] = 0x2A
tt[2 * 0x29 + 1] = 0x60
parts.append(carray('title_table', bytes(tt), 16,
                    'title mode, all 256 codes: original 314Fh for 00h-59h, Z, game table above, yellow text at 60h-7Fh/25h-29h'))

sys.path.insert(0, here)
from make_logo import compose
logo_codes, _ = compose(body, at(0x314F, 180))
parts.append(carray('title_logo', logo_codes, 40,
                    '6 rows x 40 logical codes: BOMBERNET, composed by make_logo.py from the original glyphs (1551h)'))
parts.append(carray('blast_pattern', at(0x1D02, 64), 16,
                    '4 arms (left,right,up,down) x 8 (dY,dX); original 1D02h'))
names = ['str_legend1', 'str_box_tl', 'str_box_ml', 'str_legend2', 'str_box2_t', 'str_box2_m',
         'str_box2_b', 'str_box3_t', 'str_box3_m', 'str_box3_b', 'str_down', 'str_push_space',
         'str_copyright', 'str_legend_row7', 'str_legend_row8']
a = 0x1642
for n in names:
    s = zstring(a)
    parts.append(cstring(n, s, f'original {a:04X}h'))
    a += len(s) + 1
assert a == 0x1778, hex(a)
for n, addr in (('str_hud_score', 0x2100), ('str_hud_bonus', 0x2107), ('str_hud_stage', 0x210E)):
    parts.append(cstring(n, zstring(addr), f'original {addr:04X}h'))
open(os.path.join(here, '..', 'c', 'data.c'), 'w').write('\n'.join(parts))
hdr = ['/* Generated by tools/extract_data.py - do not edit. */', '#ifndef DATA_H', '#define DATA_H',
       '#include <stdint.h>',
       'extern const uint8_t game_table[512];', 'extern const uint8_t title_table[512];',
       'extern const uint8_t title_logo[240];', 'extern const uint8_t blast_pattern[64];']
for n in names + ['str_hud_score', 'str_hud_bonus', 'str_hud_stage']:
    hdr.append(f'extern const char {n}[];')
hdr += ['#endif', '']
open(os.path.join(here, '..', 'c', 'data.h'), 'w').write('\n'.join(hdr))
print('wrote c/data.c and c/data.h')
