#!/usr/bin/env python3
"""Extract the data tables of the original bomber.mzf into c/data.c."""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
mzf = open(os.path.join(here, '..', 'bomber.mzf'), 'rb').read()
body = mzf[128:]
ORG = 0x1200
def at(a, n=1): return body[a - ORG:a - ORG + n]

def carray(name, data, per=16, comment=None):
    out = [f'/* {comment} */' if comment else '', f'const uint8_t {name}[{len(data)}] = {{']
    for i in range(0, len(data), per):
        out.append('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i + per]) + ',')
    out.append('};\n')
    return '\n'.join(o for o in out if o is not None)

def cstring(name, data, comment=None):
    """C string literal; a hex escape is closed before a following hex digit."""
    s = ''
    prev_hex = False
    for b in data:
        c = chr(b)
        if 0x20 <= b < 0x7f and c not in '"\\':
            if prev_hex and c in '0123456789abcdefABCDEF':
                s += '" "'
            s += c
            prev_hex = False
        else:
            s += f'\\x{b:02x}'
            prev_hex = True
    return (f'/* {comment} */\n' if comment else '') + f'const char {name}[] = "{s}";\n'

def zstring(a):
    b = bytearray()
    while at(a)[0]: b.append(at(a)[0]); a += 1
    return bytes(b)

parts = ['/* Generated by tools/extract_data.py from bomber.mzf - do not edit. */',
         '#include <stdint.h>', '#include "data.h"', '']
gt = bytearray(at(0x2F4F, 512))
# Players 2..4: copy the player-1 glyphs (codes 8A/8B/9A/9B standing A, 8C/8D/9C/9D
# standing B) into the unused walking rows A0..AB / B0..BB with other colours.
# Attribute = foreground<<4 | background: 1 blue, 2 red, 3 magenta, 5 cyan, 6 yellow, 7 white.
colours = [(0x20, 0x30), (0x50, 0x10), (0x60, 0x70)]
for i, (ca, cb) in enumerate(colours):
    for frame, (src, attr) in enumerate(((0x8A, ca), (0x8C, cb))):
        dst = 0xA0 + i * 4 + frame * 2
        for dx, dy in ((0, 0), (1, 0), (0, 16), (1, 16)):
            gt[2 * (dst + dx + dy)] = gt[2 * (src + dx + dy)]
            gt[2 * (dst + dx + dy) + 1] = attr
# Extra HUD letters for the multiplayer HUD in the free codes 92h..99h
# (display codes: A=01h .. Z=1Ah), white on black.
for i, ch in enumerate('PLMAYDHI'):
    gt[2 * (0x92 + i)] = ord(ch) - ord('A') + 1
    gt[2 * (0x92 + i) + 1] = 0x70
parts.append(carray('game_table', bytes(gt), 16,
                    'logical code -> (display code, attribute), game mode; original 2F4Fh, '
                    'A0h-BBh patched with player 2..4 sprites'))
parts.append(carray('title_table', at(0x314F, 180), 16,
                    'logical codes 00h-59h in title mode; original 314Fh'))
sys.path.insert(0, here)
from make_logo import compose
logo_codes, _ = compose(body, at(0x314F, 180))
parts.append(carray('title_logo', logo_codes, 40,
                    '6 rows x 40 logical codes: BOMBERNET, composed by make_logo.py from the original glyphs (1551h)'))
parts.append(carray('blast_pattern', at(0x1D02, 64), 16,
                    '4 arms (left,right,up,down) x 8 (dY,dX); original 1D02h'))
names = ['str_legend1', 'str_box_tl', 'str_box_ml', 'str_legend2', 'str_box2_t', 'str_box2_m',
         'str_box2_b', 'str_box3_t', 'str_box3_m', 'str_box3_b', 'str_down', 'str_push_space',
         'str_copyright', 'str_legend_row7', 'str_legend_row8']
a = 0x1642
for n in names:
    s = zstring(a)
    parts.append(cstring(n, s, f'original {a:04X}h'))
    a += len(s) + 1
assert a == 0x1778, hex(a)
for n, addr in (('str_hud_score', 0x2100), ('str_hud_bonus', 0x2107), ('str_hud_stage', 0x210E)):
    parts.append(cstring(n, zstring(addr), f'original {addr:04X}h'))
open(os.path.join(here, '..', 'c', 'data.c'), 'w').write('\n'.join(parts))
hdr = ['/* Generated by tools/extract_data.py - do not edit. */', '#ifndef DATA_H', '#define DATA_H',
       '#include <stdint.h>',
       'extern const uint8_t game_table[512];', 'extern const uint8_t title_table[180];',
       'extern const uint8_t title_logo[240];', 'extern const uint8_t blast_pattern[64];']
for n in names + ['str_hud_score', 'str_hud_bonus', 'str_hud_stage']:
    hdr.append(f'extern const char {n}[];')
hdr += ['#endif', '']
open(os.path.join(here, '..', 'c', 'data.h'), 'w').write('\n'.join(hdr))
print('wrote c/data.c and c/data.h')
