/* Generated by tools/make_zx_tables.py - do not edit. */
#ifndef TABLES_H
#define TABLES_H
#include <stdint.h>
extern const uint8_t zx_glyphs[632];
extern const uint8_t zx_game_tab[512];
extern const uint8_t zx_title_tab[512];
#endif
